In [39]:
import numpy as np

state = np.array([1, -.5, -.2, .5])
cov = np.array([.001, .01, .001, .01])
m_c, m_p, l = 5, 2, 0.8
force = 0
t = 0.01

def compute_x_acc(force, theta, theta_vel, theta_acc):
    x_acc = ((force - m_p * l * (theta_acc * np.cos(theta) - (theta_vel ** 2) * np.sin(theta)) * np.cos(theta)) /
            (m_c + m_p))
    return x_acc

def compute_theta_acc(force, theta, theta_vel, g=9.81):
    theta_acc = ((g * np.sin(theta) * (m_c + m_p) - (force + m_p * l * (theta_vel ** 2) * np.sin(theta)) * np.cos(theta)) /
            ((4/3) * l * (m_c + m_p) - m_p * l * (np.cos(theta)**2)))
    return theta_acc


def update_state(state_t):
    theta_acc_tt = compute_theta_acc(force, state_t[2], state_t[3])
    x_acc_tt = compute_x_acc(force, state_t[2], state_t[3], theta_acc_tt)
    
    # Compute linear velocity
    x_vel_tt = state_t[1] + x_acc_tt * t
    # Compute next position
    x_tt = state_t[0] + x_vel_tt * t
    
    # Compute angular velocity
    theta_vel_tt = state_t[3] + theta_acc_tt * t
    # Compute next theta
    theta_tt = state_t[2] + theta_vel_tt * t
    
    # Update state
    state_tt = np.array([x_tt, x_vel_tt, theta_tt, theta_vel_tt]) + cov
    
    return state_tt

def update_interval(state_init, time=1):
    state = state_init.copy()
    for _ in range(int(time/t)):
#         print("State: ", state)
        state = update_state(state)
    return state

In [42]:
state_final1 = update_interval(state, 0.1)
state_final2 = update_interval(state, 0.5)
state_final3 = update_interval(state, 1)

print(state)
print(state_final1)
print(state_final2)
print(state_final3)

[ 1.  -0.5 -0.2  0.5]
[ 0.96700665 -0.35617449 -0.14707263  0.39847163]
[0.96114303 0.1031815  0.04689016 0.53278777]
[1.13822933 0.40238265 0.75950775 2.59430921]


In [23]:
int(1/t)

100