## Task 8.1

In [254]:
# Imports
import numpy as np

# Global variables
M = 4
S = 0.01 
L = 0.3
G = 9.8

# Initial state
state = [0.3, -1]

# Compute next state
# using motion equations
def next_state_non_linear(state):
    # Compute acceleration
    new_acceleration = (G/L) * np.sin(state[0])
    
    # Compute next angle
    new_velocity = state[1] + new_acceleration * S
    
    # Compute next angular velocity
    new_angle = state[0] + new_velocity * S
        
    # Return new state
    return [new_angle, new_velocity]

print("Initial state: ", state)

for x in range(int(0.2//S)):
    state = next_state_non_linear(state)

print("Final state: ", state)

Initial state:  [0.3, -1]
Final state:  [0.2814520237292153, 0.7017407023857654]


## Task 8.2

In [255]:
A = np.matrix([[1, S], [(G/L) * S, 1]])
B = np.matrix([[0,S]]).T

In [256]:
state = np.array([[0.3, -1]]).T

for x in range(int(0.5//S)):
    state = np.dot(A, state)
print(state)

[[0.96563031]
 [5.36722952]]


## Task 8.3

In [257]:
state = np.array([[0.3, -1]]).T

actions= []
states = []

def cost_func(state):
    return float(state[0]**2)

for x in range(int(0.5//S)):
    cost = cost_func(state)
    action = float(np.sign(state[0]) * -1 * cost)
    state = np.dot(A, state) + np.dot(B, action)
    actions.append(action)
    states.append(state)
print(state)

[[0.94786935]
 [5.21056728]]


## Task 8.4

In [258]:
state = np.array([[0.3, -1]]).T

A = np.matrix([[1, S], [(G/L) * S, 1]])
B = np.matrix([[0,S]]).T
Q = np.random.rand(2,2)
R = np.random.rand(1,1)

phis = [-(np.copy(Q))] * len(states)
psis = [0] * len(states)


In [261]:
for i in range(len(states)-2, -1, -1):
    G = (phis[i+1] - np.dot(np.dot(np.dot(np.dot(phis[i+1], B), np.linalg.inv(np.dot(np.dot(B.T, phis[i+1]),B) - R)), B.T), phis[i+1]))
    phis[i] = actions[i] * G * actions[i] - Q

In [262]:
state = np.array([[0.3, -1]]).T

for i in range(int(0.5//S)):
    if (i == int(0.5//S)-1):
        break
    G = (phis[i+1] - np.dot(np.dot(np.dot(np.dot(phis[i+1], B), np.linalg.inv(np.dot(np.dot(B.T, phis[i+1]),B) - R)), B.T), phis[i+1]))
    phis[i] = actions[i] * G * actions[i] - Q
    L = np.dot(np.dot(np.dot(np.linalg.inv(np.dot(np.dot(B.T, phis[i+1]), B) - R), B.T), phis[i+1]), A)
    action = float(-np.dot(L, state))
    state = np.dot(A, state) + np.dot(B, action)
    actions[i] = action
    states[i] = state
print(state)

[[0.91438913]
 [5.06221498]]


In [205]:
state

matrix([[12.95194282],
        [73.97379886]])