## Task 8.1

In [330]:
# Imports
import numpy as np

# Global variables
M = 4
S = 0.01 
L = 0.3
G = 9.8

# Initial state
state = [0.3, -1]

# Compute next state
# using motion equations
def next_state_non_linear(state):
    # Compute acceleration
    new_acceleration = (G/L) * np.sin(state[0])
    
    # Compute next angle
    new_velocity = state[1] + new_acceleration * S
    
    # Compute next angular velocity
    new_angle = state[0] + new_velocity * S
        
    # Return new state
    return [new_angle, new_velocity]


for x in range(int(1//S)):
    state = next_state_non_linear(state)

print(state)

[5.4179566912589, 4.703197099464097]


## Task 8.2

In [331]:
A = np.matrix([[1, S], [(G/L) * S, 1]])
B = np.matrix([[0,S]]).T

In [332]:
state = np.array([[0.3, -1]]).T

for x in range(int(0.5//S)):
    state = np.dot(A, state)

print(state)

[[0.96563031]
 [5.36722952]]


## Task 8.3

In [333]:
state = np.array([[0.3, -1]]).T
interval = 0.5 # seconds
actions= []
states = []

def cost_func(state):
    return float(state[0]**2)

for x in range(int(interval//S)):
    cost = cost_func(state)
    action = float(np.sign(state[0]) * -1 * cost)
    state = np.dot(A, state) + np.dot(B, action)
    actions.append(action)
    states.append(state)

print(state)

[[0.94786935]
 [5.21056728]]


## Task 8.4

In [334]:
state = np.array([[0.3, -1]]).T

A = np.matrix([[1, S], [(G/L) * S, 1]])
B = np.matrix([[0,S]]).T
Q = np.random.rand(2,2)
R = np.random.rand(1,1)

phis = [-(np.copy(Q))] * len(states)
psis = [0] * len(states)
sigma = np.array([[.01,.04]])

In [335]:
# Recursively compute Phi and Psi
for i in range(len(states)-2, -1, -1):
    phis[i] = actions[i] * (phis[i+1] - np.dot(np.dot(np.dot(np.dot(phis[i+1], B), np.linalg.inv(np.dot(np.dot(B.T, phis[i+1]),B) - R)), B.T), phis[i+1])) * actions[i] - Q
    psis[i] = - np.trace(np.dot(sigma, phis[i+1])) + psis[i]

In [336]:
state = np.array([[0.3, -1]]).T
values = []

for i in range(int(interval//S)):
    if (i == int(0.5//S)-1):
        break
    G = (phis[i+1] - np.dot(np.dot(np.dot(np.dot(phis[i+1], B), np.linalg.inv(np.dot(np.dot(B.T, phis[i+1]),B) - R)), B.T), phis[i+1]))
    phis[i] = actions[i] * G * actions[i] - Q
    L = np.dot(np.dot(np.dot(np.linalg.inv(np.dot(np.dot(B.T, phis[i+1]), B) - R), B.T), phis[i+1]), A)
    action = float(-np.dot(L, state))
    state = np.dot(A, state) + np.dot(B, action)
    value = float(np.dot(np.dot(state.T, phis[i]), state) + psis[i])
    actions[i] = action
    states[i] = state
    values.append(value)

print(state)

[[0.91382573]
 [5.05309006]]


## Task 8.5

In [337]:
values

[-0.5109707677087613,
 -0.3903589621019586,
 -0.28812124263614913,
 -0.20265461988917194,
 -0.13261644462235248,
 -0.07689623916267951,
 -0.03459340450188683,
 -0.004999685793682457,
 0.012414410775575233,
 0.01800983178253017,
 0.011986236846576431,
 -0.005613404671191067,
 -0.03490068916366539,
 -0.07614201571059541,
 -0.1297611434859707,
 -0.19634409330948233,
 -0.276646481437874,
 -0.37160344274579526,
 -0.48234237940419533,
 -0.610198866368975,
 -0.7567361646133329,
 -0.9237689480918181,
 -1.1133920562153865,
 -1.3280153618292985,
 -1.5704062265225982,
 -1.8437415460725533,
 -2.151672136229044,
 -2.4984032738061956,
 -2.8887967440297784,
 -3.328501991134921,
 -3.8241273038641435,
 -4.3834670050800275,
 -5.015808379337531,
 -5.732354325171137,
 -6.546817599587825,
 -7.476275870244397,
 -8.542435044369276,
 -9.773555425741186,
 -11.207505438847022,
 -12.896853537382562,
 -14.91790356752144,
 -17.387571418170783,
 -20.493617443540806,
 -24.53158288045986,
 -29.86782701530367,
 -36.54